package country

//todo explain rationale for mvp using 2 digits vs structs to represent complex country type

type Countries []Country
type Country string

func (c *Country) String() string {
	return string(*c)
}

// validates a single country
func (c *Country) Validate() error {
	allCurrencies := getAllCountries()
	for _, currency := range allCurrencies {
		if currency.String() == c.String() {
			return nil
		}
	}
	return &ErrInvalidCountry{
		Country: *c,
	}
}

// getAllCountries is a helper for returning all valid currencies
// todo grep for generating this
func getAllCountries() Countries {
	return Countries{Afghanistan, Albania, Algeria, AmericanSamoa, Andorra, Angola, Anguilla, Antarctica, AntiguaandBarbuda, Argentina, Armenia, Aruba, Australia, Austria, Azerbaijan, Bahamasthe, Bahrain, Bangladesh, Barbados, Belarus, Belgium, Belize, Benin, Bermuda, Bhutan, BoliviaPlurinationalStateof, BonaireSintEustatiusandSaba, BosniaandHerzegovina, Botswana, BouvetIsland, Brazil, BritishIndianOceanTerritorythe, BruneiDarussalam, Bulgaria, BurkinaFaso, Burundi, CaboVerde, Cambodia, Cameroon, Canada, CaymanIslandsthe, CentralAfricanRepublicthe, Chad, Chile, China, ChristmasIsland, CocosKeelingIslandsthe, Colombia, Comorosthe, CongotheDemocraticRepublicofthe, Congothe, CookIslandsthe, CostaRica, Croatia, Cuba, Curacao, Cyprus, Czechia, CotedIvoire, Denmark, Djibouti, Dominica, DominicanRepublicthe, Ecuador, Egypt, ElSalvador, EquatorialGuinea, Eritrea, Estonia, Eswatini, Ethiopia, FalklandIslandstheMalvinas, FaroeIslandsthe, Fiji, Finland, France, FrenchGuiana, FrenchPolynesia, FrenchSouthernTerritoriesthe, Gabon, Gambiathe, Georgia, Germany, Ghana, Gibraltar, Greece, Greenland, Grenada, Guadeloupe, Guam, Guatemala, Guernsey, Guinea, GuineaBissau, Guyana, Haiti, HeardIslandandMcDonaldIslands, HolySeethe, Honduras, HongKong, Hungary, Iceland, India, Indonesia, IranIslamicRepublicof, Iraq, Ireland, IsleofMan, Israel, Italy, Jamaica, Japan, Jersey, Jordan, Kazakhstan, Kenya, Kiribati, KoreatheDemocraticPeoplesRepublicof, KoreatheRepublicof, Kuwait, Kyrgyzstan, LaoPeoplesDemocraticRepublicthe, Latvia, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Lithuania, Luxembourg, Macao, Madagascar, Malawi, Malaysia, Maldives, Mali, Malta, MarshallIslandsthe, Martinique, Mauritania, Mauritius, Mayotte, Mexico, MicronesiaFederatedStatesof, MoldovatheRepublicof, Monaco, Mongolia, Montenegro, Montserrat, Morocco, Mozambique, Myanmar, Namibia, Nauru, Nepal, Netherlandsthe, NewCaledonia, NewZealand, Nicaragua, Nigerthe, Nigeria, Niue, NorfolkIsland, NorthernMarianaIslandsthe, Norway, Oman, Pakistan, Palau, PalestineStateof, Panama, PapuaNewGuinea, Paraguay, Peru, Philippinesthe, Pitcairn, Poland, Portugal, PuertoRico, Qatar, RepublicofNorthMacedonia, Romania, RussianFederationthe, Rwanda, Reunion, SaintBarthelemy, SaintHelenaAscensionandTristandaCunha, SaintKittsandNevis, SaintLucia, SaintMartinFrenchpart, SaintPierreandMiquelon, SaintVincentandtheGrenadines, Samoa, SanMarino, SaoTomeandPrincipe, SaudiArabia, Senegal, Serbia, Seychelles, SierraLeone, Singapore, SintMaartenDutchpart, Slovakia, Slovenia, SolomonIslands, Somalia, SouthAfrica, SouthGeorgiaandtheSouthSandwichIslands, SouthSudan, Spain, SriLanka, Sudanthe, Suriname, SvalbardandJanMayen, Sweden, Switzerland, SyrianArabRepublic, TaiwanProvinceofChina, Tajikistan, TanzaniaUnitedRepublicof, Thailand, TimorLeste, Togo, Tokelau, Tonga, TrinidadandTobago, Tunisia, Turkey, Turkmenistan, TurksandCaicosIslandsthe, Tuvalu, Uganda, Ukraine, UnitedArabEmiratesthe, UnitedKingdomofGreatBritainandNorthernIrelandthe, UnitedStatesMinorOutlyingIslandsthe, UnitedStatesofAmericathe, Uruguay, Uzbekistan, Vanuatu, VenezuelaBolivarianRepublicof, VietNam, VirginIslandsBritish, VirginIslandsUS, WallisandFutuna, WesternSahara, Yemen, Zambia, Zimbabwe, AlandIslands}
}

const (
	Afghanistan                                      Country = "AF"
	Albania                                          Country = "AL"
	Algeria                                          Country = "DZ"
	AmericanSamoa                                    Country = "AS"
	Andorra                                          Country = "AD"
	Angola                                           Country = "AO"
	Anguilla                                         Country = "AI"
	Antarctica                                       Country = "AQ"
	AntiguaandBarbuda                                Country = "AG"
	Argentina                                        Country = "AR"
	Armenia                                          Country = "AM"
	Aruba                                            Country = "AW"
	Australia                                        Country = "AU"
	Austria                                          Country = "AT"
	Azerbaijan                                       Country = "AZ"
	Bahamasthe                                       Country = "BS"
	Bahrain                                          Country = "BH"
	Bangladesh                                       Country = "BD"
	Barbados                                         Country = "BB"
	Belarus                                          Country = "BY"
	Belgium                                          Country = "BE"
	Belize                                           Country = "BZ"
	Benin                                            Country = "BJ"
	Bermuda                                          Country = "BM"
	Bhutan                                           Country = "BT"
	BoliviaPlurinationalStateof                      Country = "BO"
	BonaireSintEustatiusandSaba                      Country = "BQ"
	BosniaandHerzegovina                             Country = "BA"
	Botswana                                         Country = "BW"
	BouvetIsland                                     Country = "BV"
	Brazil                                           Country = "BR"
	BritishIndianOceanTerritorythe                   Country = "IO"
	BruneiDarussalam                                 Country = "BN"
	Bulgaria                                         Country = "BG"
	BurkinaFaso                                      Country = "BF"
	Burundi                                          Country = "BI"
	CaboVerde                                        Country = "CV"
	Cambodia                                         Country = "KH"
	Cameroon                                         Country = "CM"
	Canada                                           Country = "CA"
	CaymanIslandsthe                                 Country = "KY"
	CentralAfricanRepublicthe                        Country = "CF"
	Chad                                             Country = "TD"
	Chile                                            Country = "CL"
	China                                            Country = "CN"
	ChristmasIsland                                  Country = "CX"
	CocosKeelingIslandsthe                           Country = "CC"
	Colombia                                         Country = "CO"
	Comorosthe                                       Country = "KM"
	CongotheDemocraticRepublicofthe                  Country = "CD"
	Congothe                                         Country = "CG"
	CookIslandsthe                                   Country = "CK"
	CostaRica                                        Country = "CR"
	Croatia                                          Country = "HR"
	Cuba                                             Country = "CU"
	Curacao                                          Country = "CW"
	Cyprus                                           Country = "CY"
	Czechia                                          Country = "CZ"
	CotedIvoire                                      Country = "CI"
	Denmark                                          Country = "DK"
	Djibouti                                         Country = "DJ"
	Dominica                                         Country = "DM"
	DominicanRepublicthe                             Country = "DO"
	Ecuador                                          Country = "EC"
	Egypt                                            Country = "EG"
	ElSalvador                                       Country = "SV"
	EquatorialGuinea                                 Country = "GQ"
	Eritrea                                          Country = "ER"
	Estonia                                          Country = "EE"
	Eswatini                                         Country = "SZ"
	Ethiopia                                         Country = "ET"
	FalklandIslandstheMalvinas                       Country = "FK"
	FaroeIslandsthe                                  Country = "FO"
	Fiji                                             Country = "FJ"
	Finland                                          Country = "FI"
	France                                           Country = "FR"
	FrenchGuiana                                     Country = "GF"
	FrenchPolynesia                                  Country = "PF"
	FrenchSouthernTerritoriesthe                     Country = "TF"
	Gabon                                            Country = "GA"
	Gambiathe                                        Country = "GM"
	Georgia                                          Country = "GE"
	Germany                                          Country = "DE"
	Ghana                                            Country = "GH"
	Gibraltar                                        Country = "GI"
	Greece                                           Country = "GR"
	Greenland                                        Country = "GL"
	Grenada                                          Country = "GD"
	Guadeloupe                                       Country = "GP"
	Guam                                             Country = "GU"
	Guatemala                                        Country = "GT"
	Guernsey                                         Country = "GG"
	Guinea                                           Country = "GN"
	GuineaBissau                                     Country = "GW"
	Guyana                                           Country = "GY"
	Haiti                                            Country = "HT"
	HeardIslandandMcDonaldIslands                    Country = "HM"
	HolySeethe                                       Country = "VA"
	Honduras                                         Country = "HN"
	HongKong                                         Country = "HK"
	Hungary                                          Country = "HU"
	Iceland                                          Country = "IS"
	India                                            Country = "IN"
	Indonesia                                        Country = "ID"
	IranIslamicRepublicof                            Country = "IR"
	Iraq                                             Country = "IQ"
	Ireland                                          Country = "IE"
	IsleofMan                                        Country = "IM"
	Israel                                           Country = "IL"
	Italy                                            Country = "IT"
	Jamaica                                          Country = "JM"
	Japan                                            Country = "JP"
	Jersey                                           Country = "JE"
	Jordan                                           Country = "JO"
	Kazakhstan                                       Country = "KZ"
	Kenya                                            Country = "KE"
	Kiribati                                         Country = "KI"
	KoreatheDemocraticPeoplesRepublicof              Country = "KP"
	KoreatheRepublicof                               Country = "KR"
	Kuwait                                           Country = "KW"
	Kyrgyzstan                                       Country = "KG"
	LaoPeoplesDemocraticRepublicthe                  Country = "LA"
	Latvia                                           Country = "LV"
	Lebanon                                          Country = "LB"
	Lesotho                                          Country = "LS"
	Liberia                                          Country = "LR"
	Libya                                            Country = "LY"
	Liechtenstein                                    Country = "LI"
	Lithuania                                        Country = "LT"
	Luxembourg                                       Country = "LU"
	Macao                                            Country = "MO"
	Madagascar                                       Country = "MG"
	Malawi                                           Country = "MW"
	Malaysia                                         Country = "MY"
	Maldives                                         Country = "MV"
	Mali                                             Country = "ML"
	Malta                                            Country = "MT"
	MarshallIslandsthe                               Country = "MH"
	Martinique                                       Country = "MQ"
	Mauritania                                       Country = "MR"
	Mauritius                                        Country = "MU"
	Mayotte                                          Country = "YT"
	Mexico                                           Country = "MX"
	MicronesiaFederatedStatesof                      Country = "FM"
	MoldovatheRepublicof                             Country = "MD"
	Monaco                                           Country = "MC"
	Mongolia                                         Country = "MN"
	Montenegro                                       Country = "ME"
	Montserrat                                       Country = "MS"
	Morocco                                          Country = "MA"
	Mozambique                                       Country = "MZ"
	Myanmar                                          Country = "MM"
	Namibia                                          Country = "NA"
	Nauru                                            Country = "NR"
	Nepal                                            Country = "NP"
	Netherlandsthe                                   Country = "NL"
	NewCaledonia                                     Country = "NC"
	NewZealand                                       Country = "NZ"
	Nicaragua                                        Country = "NI"
	Nigerthe                                         Country = "NE"
	Nigeria                                          Country = "NG"
	Niue                                             Country = "NU"
	NorfolkIsland                                    Country = "NF"
	NorthernMarianaIslandsthe                        Country = "MP"
	Norway                                           Country = "NO"
	Oman                                             Country = "OM"
	Pakistan                                         Country = "PK"
	Palau                                            Country = "PW"
	PalestineStateof                                 Country = "PS"
	Panama                                           Country = "PA"
	PapuaNewGuinea                                   Country = "PG"
	Paraguay                                         Country = "PY"
	Peru                                             Country = "PE"
	Philippinesthe                                   Country = "PH"
	Pitcairn                                         Country = "PN"
	Poland                                           Country = "PL"
	Portugal                                         Country = "PT"
	PuertoRico                                       Country = "PR"
	Qatar                                            Country = "QA"
	RepublicofNorthMacedonia                         Country = "MK"
	Romania                                          Country = "RO"
	RussianFederationthe                             Country = "RU"
	Rwanda                                           Country = "RW"
	Reunion                                          Country = "RE"
	SaintBarthelemy                                  Country = "BL"
	SaintHelenaAscensionandTristandaCunha            Country = "SH"
	SaintKittsandNevis                               Country = "KN"
	SaintLucia                                       Country = "LC"
	SaintMartinFrenchpart                            Country = "MF"
	SaintPierreandMiquelon                           Country = "PM"
	SaintVincentandtheGrenadines                     Country = "VC"
	Samoa                                            Country = "WS"
	SanMarino                                        Country = "SM"
	SaoTomeandPrincipe                               Country = "ST"
	SaudiArabia                                      Country = "SA"
	Senegal                                          Country = "SN"
	Serbia                                           Country = "RS"
	Seychelles                                       Country = "SC"
	SierraLeone                                      Country = "SL"
	Singapore                                        Country = "SG"
	SintMaartenDutchpart                             Country = "SX"
	Slovakia                                         Country = "SK"
	Slovenia                                         Country = "SI"
	SolomonIslands                                   Country = "SB"
	Somalia                                          Country = "SO"
	SouthAfrica                                      Country = "ZA"
	SouthGeorgiaandtheSouthSandwichIslands           Country = "GS"
	SouthSudan                                       Country = "SS"
	Spain                                            Country = "ES"
	SriLanka                                         Country = "LK"
	Sudanthe                                         Country = "SD"
	Suriname                                         Country = "SR"
	SvalbardandJanMayen                              Country = "SJ"
	Sweden                                           Country = "SE"
	Switzerland                                      Country = "CH"
	SyrianArabRepublic                               Country = "SY"
	TaiwanProvinceofChina                            Country = "TW"
	Tajikistan                                       Country = "TJ"
	TanzaniaUnitedRepublicof                         Country = "TZ"
	Thailand                                         Country = "TH"
	TimorLeste                                       Country = "TL"
	Togo                                             Country = "TG"
	Tokelau                                          Country = "TK"
	Tonga                                            Country = "TO"
	TrinidadandTobago                                Country = "TT"
	Tunisia                                          Country = "TN"
	Turkey                                           Country = "TR"
	Turkmenistan                                     Country = "TM"
	TurksandCaicosIslandsthe                         Country = "TC"
	Tuvalu                                           Country = "TV"
	Uganda                                           Country = "UG"
	Ukraine                                          Country = "UA"
	UnitedArabEmiratesthe                            Country = "AE"
	UnitedKingdomofGreatBritainandNorthernIrelandthe Country = "GB"
	UnitedStatesMinorOutlyingIslandsthe              Country = "UM"
	UnitedStatesofAmericathe                         Country = "US"
	Uruguay                                          Country = "UY"
	Uzbekistan                                       Country = "UZ"
	Vanuatu                                          Country = "VU"
	VenezuelaBolivarianRepublicof                    Country = "VE"
	VietNam                                          Country = "VN"
	VirginIslandsBritish                             Country = "VG"
	VirginIslandsUS                                  Country = "VI"
	WallisandFutuna                                  Country = "WF"
	WesternSahara                                    Country = "EH"
	Yemen                                            Country = "YE"
	Zambia                                           Country = "ZM"
	Zimbabwe                                         Country = "ZW"
	AlandIslands                                     Country = "AX"
)
